### ISSUE TITLE
Does not compile in latest zig version

### ISSUE THREAD

**Issue by Guigui220D** [ducdetronquito/requestz#14]
0.8.0-dev.1417+9f722f43a

I didn't try to see what didn't work because I can only code this week end and it's probably an easy fix but it seems it's the inline keyword that is deprecated.

**Comment by ducdetronquito** [comment]
Hi @Guigui220D,

I prefer to use Zig latest stable release for my projects but I understand that people like to live on the edge especially since Zig has not reached 1.0 yet.

I will create a `latest` branch on each project ([requestz](https://github.com/ducdetronquito/requestz), [h11](https://github.com/ducdetronquito/h11) and [http](https://github.com/ducdetronquito/http)) that will be compatible with Zig master branch.

I keep you in touch when it's done !

**Comment by Guigui220D** [comment]
Thanks a lot :)

**Comment by ducdetronquito** [comment]
Hi @Guigui220D

Since Zig 0.8.0 has been released recently, the master branch of requestz/h11/http can build againt it :)

As soon as I am sure that the chunked transfer encoding works fine, I will work on HTTPS (via [iguanaTLS](https://github.com/alexnask/iguanaTLS)) and hopefully make a 0.1.0 release for [gyro](https://github.com/mattnite/gyro) and [zigmod](https://github.com/nektro/zigmod).
